# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='params.proto',
  package='params',
  serialized_pb=_b('\n\x0cparams.proto\x12\x06params\"\xa2\x01\n\nInstrument\x12\x0e\n\x06symbol\x18\x01 \x02(\t\x12\x17\n\x0ftrading_enabled\x18\x02 \x02(\x08\x12\x10\n\x08\x62t_input\x18\x03 \x02(\t\x12\x15\n\rbt_input_type\x18\x04 \x02(\t\x12\x12\n\nbt_channel\x18\x05 \x02(\t\x12\x14\n\x0c\x61pply_trades\x18\x06 \x02(\x08\x12\x18\n\x10maintain_implied\x18\x07 \x02(\x08\"\xc9\x02\n\x08Strategy\x12\x0c\n\x04name\x18\x01 \x02(\t\x12&\n\ninstrument\x18\x02 \x03(\x0b\x32\x12.params.Instrument\x12\x17\n\x0ftrading_enabled\x18\x03 \x02(\x08\x12\x1a\n\x12\x65loop_cpu_affinity\x18\x04 \x02(\x05\x12\x13\n\x0bis_realtime\x18\x05 \x02(\x08\x12\x1b\n\x13oob_logger_affinity\x18\x06 \x02(\x05\x12\x1e\n\x16oob_logger_file_prefix\x18\x07 \x02(\t\x12\x12\n\nlog_timing\x18\x08 \x02(\x08\x12\x0c\n\x04\x64\x61te\x18\t \x02(\t\x12\x1a\n\x12\x63me_channel_config\x18\n \x02(\t\x12\x15\n\rsecdef_format\x18\x0b \x02(\t\x12\x13\n\x0bsecdef_root\x18\x0c \x02(\t\x12\x16\n\x0e\x65nable_oob_log\x18\r \x02(\x08\",\n\x06Params\x12\"\n\x08strategy\x18\x01 \x02(\x0b\x32\x10.params.Strategy')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INSTRUMENT = _descriptor.Descriptor(
  name='Instrument',
  full_name='params.Instrument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='params.Instrument.symbol', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trading_enabled', full_name='params.Instrument.trading_enabled', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bt_input', full_name='params.Instrument.bt_input', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bt_input_type', full_name='params.Instrument.bt_input_type', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bt_channel', full_name='params.Instrument.bt_channel', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='apply_trades', full_name='params.Instrument.apply_trades', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maintain_implied', full_name='params.Instrument.maintain_implied', index=6,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=187,
)


_STRATEGY = _descriptor.Descriptor(
  name='Strategy',
  full_name='params.Strategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='params.Strategy.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instrument', full_name='params.Strategy.instrument', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trading_enabled', full_name='params.Strategy.trading_enabled', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eloop_cpu_affinity', full_name='params.Strategy.eloop_cpu_affinity', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_realtime', full_name='params.Strategy.is_realtime', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oob_logger_affinity', full_name='params.Strategy.oob_logger_affinity', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oob_logger_file_prefix', full_name='params.Strategy.oob_logger_file_prefix', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_timing', full_name='params.Strategy.log_timing', index=7,
      number=8, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='params.Strategy.date', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cme_channel_config', full_name='params.Strategy.cme_channel_config', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secdef_format', full_name='params.Strategy.secdef_format', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secdef_root', full_name='params.Strategy.secdef_root', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_oob_log', full_name='params.Strategy.enable_oob_log', index=12,
      number=13, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=519,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='params.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strategy', full_name='params.Params.strategy', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=565,
)

_STRATEGY.fields_by_name['instrument'].message_type = _INSTRUMENT
_PARAMS.fields_by_name['strategy'].message_type = _STRATEGY
DESCRIPTOR.message_types_by_name['Instrument'] = _INSTRUMENT
DESCRIPTOR.message_types_by_name['Strategy'] = _STRATEGY
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS

Instrument = _reflection.GeneratedProtocolMessageType('Instrument', (_message.Message,), dict(
  DESCRIPTOR = _INSTRUMENT,
  __module__ = 'params_pb2'
  # @@protoc_insertion_point(class_scope:params.Instrument)
  ))
_sym_db.RegisterMessage(Instrument)

Strategy = _reflection.GeneratedProtocolMessageType('Strategy', (_message.Message,), dict(
  DESCRIPTOR = _STRATEGY,
  __module__ = 'params_pb2'
  # @@protoc_insertion_point(class_scope:params.Strategy)
  ))
_sym_db.RegisterMessage(Strategy)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), dict(
  DESCRIPTOR = _PARAMS,
  __module__ = 'params_pb2'
  # @@protoc_insertion_point(class_scope:params.Params)
  ))
_sym_db.RegisterMessage(Params)


# @@protoc_insertion_point(module_scope)
