# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='user',
  serialized_pb=_b('\n\nuser.proto\x12\x04user\"\x1d\n\x0cUserStrategy\x12\r\n\x05\x64ummy\x18\x01 \x02(\x05\"\x1f\n\x0eUserInstrument\x12\r\n\x05\x64ummy\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERSTRATEGY = _descriptor.Descriptor(
  name='UserStrategy',
  full_name='user.UserStrategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy', full_name='user.UserStrategy.dummy', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=49,
)


_USERINSTRUMENT = _descriptor.Descriptor(
  name='UserInstrument',
  full_name='user.UserInstrument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy', full_name='user.UserInstrument.dummy', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['UserStrategy'] = _USERSTRATEGY
DESCRIPTOR.message_types_by_name['UserInstrument'] = _USERINSTRUMENT

UserStrategy = _reflection.GeneratedProtocolMessageType('UserStrategy', (_message.Message,), dict(
  DESCRIPTOR = _USERSTRATEGY,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserStrategy)
  ))
_sym_db.RegisterMessage(UserStrategy)

UserInstrument = _reflection.GeneratedProtocolMessageType('UserInstrument', (_message.Message,), dict(
  DESCRIPTOR = _USERINSTRUMENT,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserInstrument)
  ))
_sym_db.RegisterMessage(UserInstrument)


# @@protoc_insertion_point(module_scope)
